//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio
    {
        public int ServicioId { get; set; }
        public string TipoServicio { get; set; }
        public System.DateTime FechaHoraServicio { get; set; }
        public bool Atendido { get; set; }
        public int MecanicoId { get; set; }
        public int VehiculoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Mecanico Mecanico { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
